name: Ci

on:
  schedule:
    - cron: "*/20 * * * *"

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: '0'
        - name: git
          run: |
            git --version
            git config user.name "GitHub Actions Bot"
            git config user.email "odyn@gmail.com"
            git commit --allow-empty -m "undetected"
            git push origin main
